insert into BANCO (banco_id, clave, nombre, descripcion) values (1, 'JMM', 'Nuveen Multi-Market', 'pellentesque at nulla suspendisse po massa volutpat');
insert into BANCO (banco_id, clave, nombre, descripcion) values (2, 'JASO', 'JA Solar Holdings', 'enim lorem ipsum dolor sit amet consec erat tortor sollicitudin');
insert into BANCO (banco_id, clave, nombre, descripcion) values (3, 'VVPR', 'VivoPower International', 'interdum eu tincidunt in leo maecenas p ultrices');
insert into BANCO (banco_id, clave, nombre, descripcion) values (4, 'FGBI', 'First Guaranty Bancshares', 'morbi a ipsum integer a nibh in qui sed tincidunt eu');
insert into BANCO (banco_id, clave, nombre, descripcion) values (5, 'BXE', 'Bellatrix ', 'quisque ut erat curabitur gravida nisi at  sed tristique in');
insert into BANCO (banco_id, clave, nombre, descripcion) values (6, 'DFT', 'Dupont Fabros ', 'montes nascetur ridiculus mus vivamus in imperdiet et commodo');
insert into BANCO (banco_id, clave, nombre, descripcion) values (7, 'GEN', 'Genesis Healthcare', 'pulvinar sed nisl nunc rhoncus d  praesent id massa');
insert into BANCO (banco_id, clave, nombre, descripcion) values (8, 'KMG', 'KMG Chemicals', 'sit amet lobortis sapien sapien non mi integer a  nulla nisl');
insert into BANCO (banco_id, clave, nombre, descripcion) values (9, 'CLBS', 'Caladrius Biosciences', 'platea dictumst etiam faucibus cursus u  vel dapibus');
insert into BANCO (banco_id, clave, nombre, descripcion) values (10, 'TENX', 'Tenax Therapeutics', 'rhoncus aliquet pulvinar sed nisl nunc rh  malesuada in imperdiet et');
insert into BANCO (banco_id, clave, nombre, descripcion) values (11, 'PEZ', 'PowerShares DWA Consumer ', 'et ultrices p  mattis odio donec vitae');
insert into BANCO (banco_id, clave, nombre, descripcion) values (12, 'DISCA', 'Discovery Communications, Inc.', 'in lectus pellentesque at nulla su  ultrices phasellus');
insert into BANCO (banco_id, clave, nombre, descripcion) values (13, 'BOTJ', 'Bank of the James Financial ', 'nullam porttitor lacus at  sit amet eleifend');
insert into BANCO (banco_id, clave, nombre, descripcion) values (14, 'MYSZ', 'My Size, Inc.', 'congue elementum in hac habitasse platea dictumst mo  in congue etiam');
insert into BANCO (banco_id, clave, nombre, descripcion) values (15, 'JTD', 'Nuveen Tax-Advantaged ', 'montes nascetur ridiculu  volutpat convallis');
insert into BANCO (banco_id, clave, nombre, descripcion) values (16, 'DUKH', 'Duke Energy Corporation', 'aliquam sit amet diam in magna bibendum im  vivamus vestibulum');
insert into BANCO (banco_id, clave, nombre, descripcion) values (17, 'DLBL', 'iPath US Treasury Long Bond ', 'platea dictumst morbi vestibu  etiam faucibus cursus');
insert into BANCO (banco_id, clave, nombre, descripcion) values (18, 'PIZ', 'PowerShares DWA Developed ', 'nullam porttit  amet eleifend');
insert into BANCO (banco_id, clave, nombre, descripcion) values (19, 'SANM', 'Sanmina Corporation', 'in faucibus orci luctus et ultrices posuere cu  nam nulla');
insert into BANCO (banco_id, clave, nombre, descripcion) values (20, 'MCEP', 'Mid-Con Energy Partners', 'in quis justo maecenas rhoncus aliquam  lacus at turpis');
