insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (1, 'YRF', 'Express Shipping Co.', 'BG09XR03B5945', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (2, 'LUQ', 'Swift Delivery Services', '15L3CYL0ED043', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (3, 'OVD', 'Speedy Parcel Express', 'VONW1FID6861R', 1);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (4, 'MDJ', 'Global Logistics Solutions', '4R5J4NG68Z5E4', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (5, 'INU', 'Fast Track Couriers', '3LLSC4QW5099N', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (6, 'OME', 'Rapid Dispatch Services', 'N9J6C40Q47UZW', 2);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (7, 'KSP', 'Prime Time Shipping', '9RGFB4T4C118E', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (8, '0', 'Quick Cargo Movers', 'MVU50897S78H5', 3);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (9, 'LVP', 'Starlight Express', '83MUX02C4BGPP', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (10, 'TIZ', 'Thunderbolt Couriers', 'SKB37L388J96T', 4);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (11, 'LST', 'Elite Logistics Group', '19FZ14WF4QPO4', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (12, 'JHS', 'Prestige Parcel Services', '27VC0162RC673', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (13, 'TID', 'Velocity Shipping Solutions', '325B88XY644LB', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (14, 'ADS', 'Swiftly Deliver', '3J16868L44CW1', 5);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (15, 'TIJ', 'Express Lane Couriers', 'H30TZ1G68PCFY', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (16, 'ARO', 'Lightning Fast Shipping', '9LK3R52E51342', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (17, 'GMO', 'Priority Parcel Express', 'F35143PS3902H', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (18, 'OGL', 'Swift Haul Logistics', '15731451CQ8EU', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (19, 'ATC', 'Rapid Response Couriers', '62LKP3Y4Y19RV', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (20, 'ISQ', 'Speedy Delivery Network', 'ERD8K9HB8V0TO', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (21, 'OTR', 'Express Shipping Co.', '20862AOPEAMIW', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (22, 'CNH', 'Swift Delivery Services', '75S9UPOAC2BS6', 3);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (23, 'MGR', 'Speedy Parcel Express', '8K50JSZ67MD0Y', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (24, 'EJH', 'Global Logistics Solutions', '007C8GW7SK54V', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (25, 'HFN', 'Fast Track Couriers', 'HL1V5501UU3Y2', 15);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (26, 'YRG', 'Rapid Dispatch Services', 'L65V247ZW957X', 16);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (27, 'HBK', 'Prime Time Shipping', '9Y033FNM7ZWHX', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (28, 'UAL', 'Quick Cargo Movers', '0U8QC0B43OQA9', 14);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (29, 'NVI', 'Starlight Express', 'C67XVBT15QSC0', null);
insert into empresa_paqueteria (empresa_paqueteria_id, clave, nombre, rfc, empresa_auxiliar) values (30, 'BSC', 'Thunderbolt Couriers', '38ARAK4LMH81F', 10);
