insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (1, sysdate - dbms_random.value(1,30), 'QQPZLPDIJ2', '8 Elmside Way');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (2, sysdate - dbms_random.value(1,30), 'VN9G75UVG8', '1231 Ruskin Avenue');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (3, sysdate - dbms_random.value(1,30), '98U4FNBX2H', '1 American Ash Point');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (4, sysdate - dbms_random.value(1,30), 'V2H9V9UGPZ', '5 Delaware Terrace');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (5, sysdate - dbms_random.value(1,30), 'DK3ZT1H5FG', '95 Schmedeman Trail');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (6, sysdate - dbms_random.value(1,30), 'CA2S2V0X13', '376 Charing Cross Circle');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (7, sysdate - dbms_random.value(1,30), '6G3E462617', '331 Bartillon Circle');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (8, sysdate - dbms_random.value(1,30), 'A8Q8N610TO', '1539 Almo Alley');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (9, sysdate - dbms_random.value(1,30), 'O7SN936A8C', '5 Marquette Road');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (10, sysdate - dbms_random.value(1,30), 'K23NN256AO', '85 Upham Center');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (11, sysdate - dbms_random.value(1,30), 'O5J045GCX9', '8 Meadow Vale Way');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (12, sysdate - dbms_random.value(1,30), 'HP62UQ0BJ1', '6 Mayer Lane');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (13, sysdate - dbms_random.value(1,30), '2W5K8JDQOB', '19352 Welch Point');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (14, sysdate - dbms_random.value(1,30), '962B2J331G', '5625 Dottie Alley');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (15, sysdate - dbms_random.value(1,30), 'SO12QX949H', '72880 Fordem Drive');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (16, sysdate - dbms_random.value(1,30), '9O4VV2LVY8', '7 Sauthoff Avenue');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (17, sysdate - dbms_random.value(1,30), '3550RXQ31W', '39507 Oriole Circle');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (18, sysdate - dbms_random.value(1,30), 'E491MKIU10', '143 Bultman Point');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (19, sysdate - dbms_random.value(1,30), '6N8D3GFTBU', '4889 Farmco Center');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (20, sysdate - dbms_random.value(1,30), '5E85NF46QB', '35473 Hazelcrest Road');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (21, sysdate - dbms_random.value(1,30), 'YPJ39R8361', '8279 Stephen Drive');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (22, sysdate - dbms_random.value(1,30), '6414P2Z846', '9491 Old Shore Place');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (23, sysdate - dbms_random.value(1,30), '11DRC6LUKG', '3 New Castle Center');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (24, sysdate - dbms_random.value(1,30), '001433T061', '6 Chinook Circle');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (25, sysdate - dbms_random.value(1,30), 'V9Y2IX6B98', '55 Vahlen Court');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (26, sysdate - dbms_random.value(1,30), 'HE182000CN', '14 Clemons Alley');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (27, sysdate - dbms_random.value(1,30), '93W928G689', '02 Melvin Park');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (28, sysdate - dbms_random.value(1,30), 'H50Q9BDEC1', '09100 Eagan Place');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (29, sysdate - dbms_random.value(1,30), '047N4AQ874', '0 Roxbury Crossing');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (30, sysdate - dbms_random.value(1,30), 'BCE72JK2LD', '2 Thackeray Plaza');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (31, sysdate - dbms_random.value(1,30), '2ZL7N12K19', '870 Sycamore Plaza');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (32, sysdate - dbms_random.value(1,30), 'Z528E15IIU', '72 Hagan Way');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (33, sysdate - dbms_random.value(1,30), '8G70Y0M02V', '26 Dawn Alley');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (34, sysdate - dbms_random.value(1,30), '3F4MHHY7E6', '7141 Myrtle Circle');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (35, sysdate - dbms_random.value(1,30), 'D440500C2D', '9857 Ridge Oak Place');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (36, sysdate - dbms_random.value(1,30), '203FJ27MD4', '48356 Brown Center');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (37, sysdate - dbms_random.value(1,30), '65162UM5BA', '552 Burrows Plaza');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (38, sysdate - dbms_random.value(1,30), 'Q939S6U019', '60 Mallard Park');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (39, sysdate - dbms_random.value(1,30), '29OV470UMB', '86 Northview Lane');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (40, sysdate - dbms_random.value(1,30), 'LNK03VKAII', '6 Truax Terrace');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (41, sysdate - dbms_random.value(1,30), '9830X3370A', '52 Evergreen Place');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (42, sysdate - dbms_random.value(1,30), 'N7E28N462S', '3339 Garrison Trail');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (43, sysdate - dbms_random.value(1,30), 'BY8K0Y14L3', '2 Surrey Circle');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (44, sysdate - dbms_random.value(1,30), 'SOT1R81YDO', '85393 Delaware Court');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (45, sysdate - dbms_random.value(1,30), 'B5P79V70C5', '99 Debra Crossing');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (46, sysdate - dbms_random.value(1,30), '3B6VL8G0SQ', '99224 Hagan Alley');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (47, sysdate - dbms_random.value(1,30), '88U5DP8N88', '479 Namekagon Trail');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (48, sysdate - dbms_random.value(1,30), 'YNG9W7033R', '37 Cordelia Parkway');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (49, sysdate - dbms_random.value(1,30), 'BC5J994ZE6', '9534 Weeping Birch Terrace');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (50, sysdate - dbms_random.value(1,30), 'N1X0V96S3F', '4 Lindbergh Hill');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (51, sysdate - dbms_random.value(1,30), 'RHEY6T097P', '2 Lotheville Road');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (52, sysdate - dbms_random.value(1,30), 'E7WK9FD9D9', '4839 Troy Avenue');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (53, sysdate - dbms_random.value(1,30), 'TY8CUJ7KE0', '4632 Jenifer Center');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (54, sysdate - dbms_random.value(1,30), 'XEDJ1AX695', '60 Manley Hill');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (55, sysdate - dbms_random.value(1,30), '647009ZNZ3', '71543 Golf Course Lane');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (56, sysdate - dbms_random.value(1,30), '3LR393DD0R', '87176 Stang Lane');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (57, sysdate - dbms_random.value(1,30), 'A719L46F86', '85058 Eastlawn Trail');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (58, sysdate - dbms_random.value(1,30), '053886ULWS', '83781 Mitchell Crossing');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (59, sysdate - dbms_random.value(1,30), '1F80G8K113', '194 Knutson Center');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (60, sysdate - dbms_random.value(1,30), 'LK842AT190', '1 Delladonna Lane');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (61, sysdate - dbms_random.value(1,30), 'Q32C0A6OKL', '7944 Village Park');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (62, sysdate - dbms_random.value(1,30), '79FI8H57B6', '038 Del Sol Plaza');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (63, sysdate - dbms_random.value(1,30), 'M29F6MEGR5', '1 Daystar Point');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (64, sysdate - dbms_random.value(1,30), 'L4R6TOKXGI', '1 Forster Place');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (65, sysdate - dbms_random.value(1,30), '7I38PW1P4O', '46 Sugar Court');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (66, sysdate - dbms_random.value(1,30), '4485TTU4JR', '43 Mayer Terrace');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (67, sysdate - dbms_random.value(1,30), '60VT7YUTX9', '136 Vahlen Street');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (68, sysdate - dbms_random.value(1,30), 'OHJ0583UTI', '1 Springs Hill');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (69, sysdate - dbms_random.value(1,30), 'N8UVG8800Y', '44 Schlimgen Crossing');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (70, sysdate - dbms_random.value(1,30), '82B80D1ZC0', '898 Shasta Avenue');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (71, sysdate - dbms_random.value(1,30), '492M8IKW0C', '92 Quincy Drive');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (72, sysdate - dbms_random.value(1,30), '58BR06IQMW', '60 Jay Plaza');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (73, sysdate - dbms_random.value(1,30), 'N2H77415WZ', '1028 Thierer Alley');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (74, sysdate - dbms_random.value(1,30), 'QSV8480AZ9', '66 Valley Edge Center');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (75, sysdate - dbms_random.value(1,30), 'IKWSKV0QBN', '3777 High Crossing Way');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (76, sysdate - dbms_random.value(1,30), '521PC0G916', '2678 Atwood Way');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (77, sysdate - dbms_random.value(1,30), '0XYAPMS148', '50 Killdeer Street');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (78, sysdate - dbms_random.value(1,30), '61HIW108J7', '0 Haas Trail');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (79, sysdate - dbms_random.value(1,30), '39L3DQ56FB', '02 Mallory Pass');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (80, sysdate - dbms_random.value(1,30), '82I5I9F1P7', '47201 Russell Plaza');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (81, sysdate - dbms_random.value(1,30), '5E850XHMFL', '9369 Dexter Drive');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (82, sysdate - dbms_random.value(1,30), 'WVP1G3VLA1', '8 School Crossing');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (83, sysdate - dbms_random.value(1,30), 'J0GP0N4002', '52385 Doe Crossing Street');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (84, sysdate - dbms_random.value(1,30), 'BHQAN4F7IN', '64737 Grim Plaza');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (85, sysdate - dbms_random.value(1,30), 'K4820CX9QR', '9699 Namekagon Parkway');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (86, sysdate - dbms_random.value(1,30), 'Q73C8SH9W5', '117 Dapin Pass');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (87, sysdate - dbms_random.value(1,30), '68G5240ETQ', '6080 Pond Alley');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (88, sysdate - dbms_random.value(1,30), '12F0814TOP', '07 1st Plaza');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (89, sysdate - dbms_random.value(1,30), '8AI9EZS77S', '63 David Avenue');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (90, sysdate - dbms_random.value(1,30), 'BC00JHXHUQ', '90 Messerschmidt Junction');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (91, sysdate - dbms_random.value(1,30), '32JMW97QP7', '4763 Shoshone Parkway');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (92, sysdate - dbms_random.value(1,30), 'T612U1IOAS', '79 Kingsford Center');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (93, sysdate - dbms_random.value(1,30), '1S75CJQO44', '05470 Spohn Hill');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (94, sysdate - dbms_random.value(1,30), 'FZM00767DR', '637 Sauthoff Crossing');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (95, sysdate - dbms_random.value(1,30), '8W39220JIZ', '941 Butterfield Plaza');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (96, sysdate - dbms_random.value(1,30), 'V6AVNI7R6L', '722 Muir Road');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (97, sysdate - dbms_random.value(1,30), 'LAO65TQ6L6', '34216 Moland Point');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (98, sysdate - dbms_random.value(1,30), '4EB59BJ78T', '6 Pine View Road');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (99, sysdate - dbms_random.value(1,30), '38G6BW7369', '8 Loftsgordon Center');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (100, sysdate - dbms_random.value(1,30), '94369I0XHD', '13031 Mandrake Alley');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (101, sysdate - dbms_random.value(1,30), 'O92W0Z7X6O', '987 Thierer Alley');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (102, sysdate - dbms_random.value(1,30), 'O4GD2QH119', '87719 Nobel Lane');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (103, sysdate - dbms_random.value(1,30), '6K91MPUVN4', '0 Birchwood Drive');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (104, sysdate - dbms_random.value(1,30), 'Y76HU5275J', '65 Badeau Circle');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (105, sysdate - dbms_random.value(1,30), 'TA9EY8DHF4', '47758 Esker Place');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (106, sysdate - dbms_random.value(1,30), '8JPANOSMCF', '6 Kenwood Place');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (107, sysdate - dbms_random.value(1,30), 'HS22CZ7600', '47 Pleasure Crossing');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (108, sysdate - dbms_random.value(1,30), 'A093XOW656', '285 Utah Avenue');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (109, sysdate - dbms_random.value(1,30), '6L3534TZ02', '52 Commercial Way');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (110, sysdate - dbms_random.value(1,30), '81412754N1', '1 Gerald Point');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (111, sysdate - dbms_random.value(1,30), 'V8E27XQ8AE', '1605 Tony Place');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (112, sysdate - dbms_random.value(1,30), 'R4LPQQN45Y', '1 Mcguire Drive');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (113, sysdate - dbms_random.value(1,30), 'A4O5DZRP24', '17822 Dovetail Point');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (114, sysdate - dbms_random.value(1,30), 'Z3G01D07SX', '00078 Oakridge Drive');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (115, sysdate - dbms_random.value(1,30), 'E34EQC2O91', '56 Monument Way');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (116, sysdate - dbms_random.value(1,30), 'SJ7LU1CABH', '49691 Straubel Trail');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (117, sysdate - dbms_random.value(1,30), 'OU8IZZI40G', '199 Lunder Way');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (118, sysdate - dbms_random.value(1,30), 'F4G6DU71W7', '4 Forest Run Road');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (119, sysdate - dbms_random.value(1,30), 'ZPXR51S7ES', '90 Glacier Hill Avenue');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (120, sysdate - dbms_random.value(1,30), '377W3Y94S7', '12 Anderson Avenue');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (121, sysdate - dbms_random.value(1,30), '02YGKPQFN4', '707 Manufacturers Trail');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (122, sysdate - dbms_random.value(1,30), 'NR9WRPKD14', '96572 Canary Park');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (123, sysdate - dbms_random.value(1,30), '87DFTC5IQ0', '4208 Haas Place');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (124, sysdate - dbms_random.value(1,30), 'QP78NREZS5', '4 Elmside Crossing');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (125, sysdate - dbms_random.value(1,30), '870WHR8RED', '85217 Dovetail Circle');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (126, sysdate - dbms_random.value(1,30), 'X6OF971B6H', '8158 Grayhawk Point');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (127, sysdate - dbms_random.value(1,30), '047KH054V2', '3733 Jana Road');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (128, sysdate - dbms_random.value(1,30), '461BYE6613', '02646 Corscot Court');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (129, sysdate - dbms_random.value(1,30), 'ST84PNP13J', '9 Buell Park');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (130, sysdate - dbms_random.value(1,30), '5KU7I2N6N9', '26 Calypso Center');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (131, sysdate - dbms_random.value(1,30), '5W713LV9Z8', '78 Pine View Point');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (132, sysdate - dbms_random.value(1,30), 'YL7I7IRWJ2', '78 Northland Terrace');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (133, sysdate - dbms_random.value(1,30), 'V2KMSW9X52', '61 Old Gate Junction');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (134, sysdate - dbms_random.value(1,30), 'E3RPBN2SE3', '7180 8th Way');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (135, sysdate - dbms_random.value(1,30), '0P017ZQ37J', '2 Talmadge Road');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (136, sysdate - dbms_random.value(1,30), 'LY0D48FNSO', '63 Rockefeller Terrace');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (137, sysdate - dbms_random.value(1,30), 'TNMC0P8L84', '53450 Daystar Pass');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (138, sysdate - dbms_random.value(1,30), '0V2U7AVJN5', '647 La Follette Place');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (139, sysdate - dbms_random.value(1,30), 'V5D0JQ1EIQ', '5 Blue Bill Park Terrace');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (140, sysdate - dbms_random.value(1,30), 'WY7L1H3535', '6 Meadow Valley Plaza');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (141, sysdate - dbms_random.value(1,30), '80R6YK27VP', '03 Manley Avenue');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (142, sysdate - dbms_random.value(1,30), 'KN56DDI79W', '2 Merchant Way');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (143, sysdate - dbms_random.value(1,30), '2LX1Z08SP3', '295 Havey Junction');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (144, sysdate - dbms_random.value(1,30), 'UT43A98QVN', '1 Utah Road');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (145, sysdate - dbms_random.value(1,30), '4K2OT9UN00', '538 Larry Crossing');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (146, sysdate - dbms_random.value(1,30), '7X046MEU71', '91364 Merry Avenue');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (147, sysdate - dbms_random.value(1,30), 'ON28979WS8', '4 Alpine Court');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (148, sysdate - dbms_random.value(1,30), '8684D1067Q', '280 Porter Court');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (149, sysdate - dbms_random.value(1,30), '5L623X0C7N', '71 Nobel Avenue');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (150, sysdate - dbms_random.value(1,30), '4R1983QMMG', '49 Randy Place');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (151, sysdate - dbms_random.value(1,30), 'E0EP77AG86', '49 Shopko Terrace');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (152, sysdate - dbms_random.value(1,30), '8EMOR54RGK', '76 Park Meadow Street');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (153, sysdate - dbms_random.value(1,30), '52D12N1NP3', '3821 Farwell Park');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (154, sysdate - dbms_random.value(1,30), 'VT853O0W06', '3 Fremont Circle');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (155, sysdate - dbms_random.value(1,30), 'FTVEV0ZY07', '67 Declaration Lane');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (156, sysdate - dbms_random.value(1,30), 'ZI77U83MAU', '575 Little Fleur Way');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (157, sysdate - dbms_random.value(1,30), 'KMH7HM6SM5', '96 Tony Park');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (158, sysdate - dbms_random.value(1,30), 'SWCT4H6TXU', '93585 Helena Road');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (159, sysdate - dbms_random.value(1,30), 'GIO1T4FEP6', '816 Portage Center');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (160, sysdate - dbms_random.value(1,30), '6DL7E74S35', '1 Boyd Lane');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (161, sysdate - dbms_random.value(1,30), 'MSGT3UC136', '1 Dapin Park');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (162, sysdate - dbms_random.value(1,30), 'BBT4YREE35', '5523 Dahle Circle');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (163, sysdate - dbms_random.value(1,30), 'Z047C3865V', '2 Stuart Court');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (164, sysdate - dbms_random.value(1,30), '9A5655983Y', '1085 Blue Bill Park Place');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (165, sysdate - dbms_random.value(1,30), 'ID5W5NB2Y8', '369 Grim Place');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (166, sysdate - dbms_random.value(1,30), 'UTZB3Y2944', '537 Derek Alley');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (167, sysdate - dbms_random.value(1,30), 'OLV28R09NV', '584 Cascade Plaza');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (168, sysdate - dbms_random.value(1,30), 'UK12VV1412', '89 Buhler Lane');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (169, sysdate - dbms_random.value(1,30), 'DFEE49N3SV', '88 Bobwhite Place');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (170, sysdate - dbms_random.value(1,30), 'QYEO322862', '03790 Judy Alley');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (171, sysdate - dbms_random.value(1,30), 'OW1ODG8006', '14162 Burning Wood Point');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (172, sysdate - dbms_random.value(1,30), 'GLZTD62YZ3', '2 John Wall Alley');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (173, sysdate - dbms_random.value(1,30), '380NG0Z3PN', '5478 Village Plaza');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (174, sysdate - dbms_random.value(1,30), 'P0I3XK77W6', '9833 Jay Way');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (175, sysdate - dbms_random.value(1,30), '48Y7AQ505D', '5 Monterey Point');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (176, sysdate - dbms_random.value(1,30), 'I3U40RRC5O', '1 Weeping Birch Point');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (177, sysdate - dbms_random.value(1,30), 'HSS839C76O', '16500 Di Loreto Terrace');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (178, sysdate - dbms_random.value(1,30), '6C9JV77AGQ', '2 New Castle Road');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (179, sysdate - dbms_random.value(1,30), 'O11SUZ7GW4', '04354 5th Trail');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (180, sysdate - dbms_random.value(1,30), '33AN11X3OH', '743 Hollow Ridge Parkway');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (181, sysdate - dbms_random.value(1,30), '61WYNG0OTC', '897 Springview Plaza');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (182, sysdate - dbms_random.value(1,30), 'UYE30G7INR', '29 Mayer Court');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (183, sysdate - dbms_random.value(1,30), '32T07GXI34', '8 Mifflin Trail');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (184, sysdate - dbms_random.value(1,30), 'RVH210ZU66', '2 Cardinal Hill');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (185, sysdate - dbms_random.value(1,30), 'MOSGV90WI3', '044 Green Park');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (186, sysdate - dbms_random.value(1,30), '26QJNN5BHU', '27 Petterle Road');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (187, sysdate - dbms_random.value(1,30), 'L1X8F9VWY6', '3 Dorton Plaza');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (188, sysdate - dbms_random.value(1,30), '3SL8010P1F', '714 7th Avenue');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (189, sysdate - dbms_random.value(1,30), '5GMOLS24V6', '00927 Veith Alley');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (190, sysdate - dbms_random.value(1,30), '4LNRI192VQ', '6860 Center Pass');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (191, sysdate - dbms_random.value(1,30), 'RW94E0480S', '33 Dixon Avenue');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (192, sysdate - dbms_random.value(1,30), 'V573W616Z4', '7994 Sommers Crossing');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (193, sysdate - dbms_random.value(1,30), 'J472FMZ09N', '9180 Lillian Parkway');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (194, sysdate - dbms_random.value(1,30), '4KKM7GFZ3D', '1 Springs Lane');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (195, sysdate - dbms_random.value(1,30), '6VW6T40DUC', '97272 Park Meadow Hill');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (196, sysdate - dbms_random.value(1,30), 'X5WT58YX93', '5 Hollow Ridge Court');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (197, sysdate - dbms_random.value(1,30), 'CTP1YJF37K', '17033 Bay Hill');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (198, sysdate - dbms_random.value(1,30), 'I3I033D2L6', '1 Erie Lane');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (199, sysdate - dbms_random.value(1,30), '88W52OW065', '17 Carey Court');
insert into orden_compra (orden_compra_id, fecha, folio, direccion_entrega) values (200, sysdate - dbms_random.value(1,30), 'W4TLW221U8', '0 Farwell Circle');
