insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (1, 4, 'ipsum aliquam non mauris morbi non lectus aliquam sit amet', 185, 435);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (2, 9, 'ultrices posuere cubilia curae nulla', 6, 360);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (3, 1, 'molestie hendrerit at vulputate vitae', 231, 482);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (4, 2, 'risus semper porta volutpat quam pede', 226, 214);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (5, 4, 'porttitor id consequat in consequat ut nulla sed', 123, 276);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (6, 7, 'vulputate luctus cum sociis natoque penatibus et magnis', 137, 207);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (7, 10, 'laoreet ut rhoncus aliquet pulvinar sed', 61, 466);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (8, 9, 'egestas metus aenean fermentum donec ut mauris eget', 187, 474);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (9, 1, 'ultrices posuere cubilia curae duis faucibus accumsan odio', 15, 422);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (10, 4, 'hendrerit at vulputate vitae nisl aenean lectus', 181, 306);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (11, 9, 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi', 190, 276);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (12, 0, 'morbi vel lectus in quam', 23, 359);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (13, 3, 'in hac habitasse platea dictumst etiam faucibus cursus urna ut', 176, 362);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (14, 5, 'eget orci vehicula condimentum curabitur in libero ut massa', 229, 358);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (15, 0, 'rhoncus aliquam lacus morbi quis', 97, 316);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (16, 4, 'ipsum dolor sit amet consectetuer adipiscing elit', 54, 261);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (17, 6, 'ipsum aliquam non mauris morbi non lectus aliquam sit', 79, 388);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (18, 6, 'a suscipit nulla elit ac', 7, 487);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (19, 3, 'feugiat non pretium quis lectus suspendisse potenti in eleifend', 174, 216);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (20, 1, 'magnis dis parturient montes nascetur ridiculus mus vivamus', 128, 442);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (21, 5, 'nulla integer pede justo lacinia eget tincidunt', 64, 280);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (22, 8, 'blandit mi in porttitor pede', 24, 474);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (23, 2, 'est donec odio justo sollicitudin ut suscipit', 203, 394);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (24, 6, 'congue vivamus metus arcu adipiscing', 179, 440);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (25, 0, 'vitae ipsum aliquam non mauris', 62, 202);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (26, 0, 'massa volutpat convallis morbi odio odio elementum eu interdum eu', 175, 303);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (27, 6, 'augue aliquam erat volutpat in congue etiam justo etiam pretium', 184, 275);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (28, 4, 'lorem ipsum dolor sit amet consectetuer', 136, 479);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (29, 10, 'at nibh in hac habitasse', 113, 251);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (30, 5, 'leo odio porttitor id consequat in consequat ut', 163, 411);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (31, 10, 'non pretium quis lectus suspendisse potenti', 1, 239);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (32, 7, 'sit amet diam in magna', 209, 489);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (33, 1, 'quam nec dui luctus rutrum nulla tellus in', 49, 457);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (34, 6, 'augue quam sollicitudin vitae consectetuer eget rutrum at lorem', 9, 415);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (35, 6, 'turpis sed ante vivamus tortor', 60, 269);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (36, 6, 'tortor duis mattis egestas metus aenean fermentum donec ut mauris', 91, 244);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (37, 7, 'quam fringilla rhoncus mauris enim', 166, 442);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (38, 1, 'ante vivamus tortor duis mattis egestas metus aenean', 76, 436);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (39, 10, 'dui nec nisi volutpat eleifend donec', 9, 497);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (40, 5, 'curabitur at ipsum ac tellus semper interdum', 36, 488);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (41, 2, 'pulvinar sed nisl nunc rhoncus', 214, 450);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (42, 4, 'diam cras pellentesque volutpat dui maecenas tristique', 110, 267);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (43, 9, 'duis bibendum morbi non quam nec dui luctus rutrum nulla', 143, 314);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (44, 3, 'augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer', 228, 368);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (45, 7, 'cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', 245, 227);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (46, 2, 'massa tempor convallis nulla neque', 180, 482);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (47, 2, 'habitasse platea dictumst etiam faucibus', 79, 230);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (48, 4, 'augue aliquam erat volutpat in congue etiam justo', 27, 411);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (49, 1, 'sagittis sapien cum sociis natoque penatibus et magnis', 211, 425);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (50, 7, 'et ultrices posuere cubilia curae nulla dapibus dolor', 199, 461);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (51, 4, 'porttitor id consequat in consequat ut nulla sed accumsan', 109, 211);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (52, 9, 'elementum in hac habitasse platea dictumst morbi', 48, 414);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (53, 3, 'eu nibh quisque id justo sit', 21, 299);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (54, 10, 'blandit nam nulla integer pede justo lacinia eget', 6, 213);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (55, 6, 'praesent blandit nam nulla integer pede justo lacinia eget', 226, 352);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (56, 4, 'aliquet at feugiat non pretium quis lectus suspendisse', 137, 319);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (57, 8, 'venenatis tristique fusce congue diam id ornare imperdiet sapien urna', 249, 437);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (58, 10, 'odio odio elementum eu interdum eu tincidunt in leo', 110, 345);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (59, 7, 'volutpat sapien arcu sed augue aliquam', 93, 218);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (60, 6, 'odio donec vitae nisi nam ultrices libero non', 188, 282);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (61, 0, 'luctus ultricies eu nibh quisque', 146, 344);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (62, 2, 'nec nisi volutpat eleifend donec ut dolor morbi vel', 143, 481);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (63, 5, 'velit vivamus vel nulla eget eros elementum pellentesque quisque porta', 1, 428);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (64, 8, 'at lorem integer tincidunt ante vel', 11, 400);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (65, 0, 'vivamus in felis eu sapien cursus', 145, 293);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (66, 8, 'sed vestibulum sit amet cursus', 144, 223);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (67, 0, 'volutpat sapien arcu sed augue aliquam erat volutpat', 239, 379);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (68, 1, 'vulputate elementum nullam varius nulla facilisi cras non', 250, 457);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (69, 8, 'at vulputate vitae nisl aenean lectus pellentesque', 132, 362);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (70, 3, 'ipsum integer a nibh in quis justo maecenas rhoncus', 94, 297);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (71, 1, 'felis donec semper sapien a libero', 44, 208);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (72, 10, 'lectus in quam fringilla rhoncus', 136, 431);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (73, 10, 'lacinia aenean sit amet justo morbi ut odio cras mi', 182, 349);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (74, 9, 'morbi ut odio cras mi pede malesuada in imperdiet', 81, 226);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (75, 0, 'lectus pellentesque at nulla suspendisse potenti cras', 48, 209);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (76, 3, 'tincidunt ante vel ipsum praesent blandit lacinia erat', 229, 489);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (77, 1, 'eget nunc donec quis orci eget', 250, 341);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (78, 9, 'sit amet nunc viverra dapibus nulla suscipit ligula in lacus', 76, 291);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (79, 10, 'id sapien in sapien iaculis congue vivamus', 92, 352);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (80, 10, 'enim leo rhoncus sed vestibulum sit', 210, 465);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (81, 6, 'vestibulum ante ipsum primis in', 142, 305);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (82, 9, 'est lacinia nisi venenatis tristique fusce congue diam id', 186, 365);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (83, 5, 'mus vivamus vestibulum sagittis sapien cum sociis natoque', 165, 483);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (84, 0, 'vitae consectetuer eget rutrum at lorem integer tincidunt ante', 167, 220);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (85, 8, 'ac tellus semper interdum mauris ullamcorper', 197, 490);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (86, 10, 'erat id mauris vulputate elementum nullam varius', 55, 400);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (87, 4, 'lectus in est risus auctor sed tristique in', 191, 377);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (88, 1, 'nunc viverra dapibus nulla suscipit', 189, 458);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (89, 7, 'non mattis pulvinar nulla pede ullamcorper', 88, 396);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (90, 7, 'quis justo maecenas rhoncus aliquam lacus morbi', 199, 370);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (91, 9, 'erat fermentum justo nec condimentum neque sapien', 248, 424);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (92, 2, 'nulla facilisi cras non velit nec nisi vulputate', 95, 401);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (93, 4, 'morbi a ipsum integer a nibh', 234, 441);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (94, 7, 'sollicitudin ut suscipit a feugiat et eros vestibulum ac est', 228, 318);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (95, 6, 'parturient montes nascetur ridiculus mus etiam vel augue vestibulum', 93, 323);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (96, 5, 'dapibus augue vel accumsan tellus', 149, 259);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (97, 6, 'sed tincidunt eu felis fusce', 116, 452);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (98, 4, 'luctus et ultrices posuere cubilia curae donec pharetra magna', 139, 352);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (99, 9, 'mauris eget massa tempor convallis nulla neque libero convallis eget', 122, 230);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (100, 7, 'diam erat fermentum justo nec condimentum', 139, 412);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (101, 5, 'mus etiam vel augue vestibulum rutrum rutrum', 210, 374);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (102, 7, 'risus dapibus augue vel accumsan tellus nisi eu', 90, 411);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (103, 3, 'posuere cubilia curae mauris viverra', 163, 270);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (104, 7, 'odio justo sollicitudin ut suscipit a feugiat et eros', 176, 495);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (105, 9, 'integer aliquet massa id lobortis convallis tortor risus dapibus', 233, 339);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (106, 4, 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer', 123, 296);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (107, 9, 'ut mauris eget massa tempor convallis nulla neque libero', 227, 241);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (108, 10, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus', 79, 272);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (109, 9, 'ut massa volutpat convallis morbi odio odio elementum eu interdum', 182, 299);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (110, 6, 'sit amet sapien dignissim vestibulum vestibulum ante ipsum primis', 244, 200);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (111, 4, 'id pretium iaculis diam erat fermentum', 200, 435);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (112, 5, 'duis ac nibh fusce lacus', 89, 418);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (113, 5, 'justo in hac habitasse platea dictumst etiam faucibus cursus', 106, 290);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (114, 3, 'libero quis orci nullam molestie nibh', 165, 235);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (115, 7, 'sapien varius ut blandit non interdum in ante vestibulum', 94, 262);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (116, 2, 'ultrices posuere cubilia curae donec pharetra magna', 5, 359);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (117, 10, 'libero quis orci nullam molestie nibh in', 228, 458);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (118, 5, 'id turpis integer aliquet massa id lobortis convallis', 8, 480);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (119, 9, 'purus aliquet at feugiat non', 143, 370);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (120, 8, 'elementum eu interdum eu tincidunt in leo maecenas', 1, 375);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (121, 4, 'sit amet eros suspendisse accumsan', 199, 474);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (122, 6, 'quis turpis eget elit sodales', 84, 297);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (123, 10, 'ac tellus semper interdum mauris ullamcorper purus sit amet', 157, 368);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (124, 4, 'vel pede morbi porttitor lorem id', 213, 286);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (125, 9, 'elementum in hac habitasse platea dictumst morbi', 154, 376);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (126, 2, 'sapien urna pretium nisl ut volutpat sapien arcu sed', 37, 375);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (127, 8, 'integer aliquet massa id lobortis convallis tortor risus dapibus', 81, 365);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (128, 9, 'ac est lacinia nisi venenatis tristique fusce congue diam id', 223, 432);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (129, 0, 'pulvinar sed nisl nunc rhoncus dui', 85, 403);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (130, 0, 'id consequat in consequat ut nulla', 192, 434);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (131, 9, 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at', 221, 298);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (132, 8, 'duis faucibus accumsan odio curabitur convallis duis consequat', 182, 452);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (133, 9, 'cras mi pede malesuada in imperdiet et commodo vulputate', 74, 231);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (134, 6, 'sodales scelerisque mauris sit amet eros', 8, 330);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (135, 5, 'lacus purus aliquet at feugiat non pretium quis lectus suspendisse', 101, 368);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (136, 7, 'augue vestibulum ante ipsum primis in', 236, 264);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (137, 5, 'lacinia nisi venenatis tristique fusce congue diam id', 125, 278);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (138, 5, 'aliquet at feugiat non pretium quis lectus suspendisse', 172, 235);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (139, 5, 'aliquam lacus morbi quis tortor id', 50, 466);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (140, 6, 'lectus vestibulum quam sapien varius ut', 74, 311);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (141, 8, 'vel augue vestibulum rutrum rutrum neque aenean', 206, 456);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (142, 5, 'leo pellentesque ultrices mattis odio', 245, 474);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (143, 4, 'tristique in tempus sit amet sem fusce', 203, 410);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (144, 8, 'curae duis faucibus accumsan odio', 102, 408);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (145, 6, 'sapien cursus vestibulum proin eu', 173, 327);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (146, 1, 'arcu libero rutrum ac lobortis vel', 28, 374);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (147, 2, 'donec odio justo sollicitudin ut suscipit a', 202, 364);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (148, 10, 'vestibulum sagittis sapien cum sociis', 163, 261);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (149, 10, 'velit id pretium iaculis diam erat fermentum justo nec', 169, 335);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (150, 6, 'dictumst etiam faucibus cursus urna ut tellus nulla', 110, 331);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (151, 6, 'amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque', 30, 390);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (152, 9, 'diam neque vestibulum eget vulputate', 72, 371);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (153, 4, 'amet cursus id turpis integer aliquet massa id lobortis convallis', 181, 397);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (154, 8, 'ante ipsum primis in faucibus orci', 60, 319);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (155, 0, 'blandit nam nulla integer pede', 143, 346);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (156, 3, 'ultrices posuere cubilia curae duis faucibus', 128, 250);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (157, 5, 'mauris ullamcorper purus sit amet nulla quisque arcu libero', 44, 213);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (158, 4, 'massa id nisl venenatis lacinia aenean sit amet justo', 111, 402);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (159, 5, 'sed interdum venenatis turpis enim blandit mi in porttitor pede', 8, 428);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (160, 1, 'nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque', 157, 329);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (161, 1, 'pellentesque viverra pede ac diam cras', 78, 439);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (162, 1, 'facilisi cras non velit nec', 84, 465);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (163, 1, 'nibh in hac habitasse platea', 236, 461);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (164, 9, 'condimentum curabitur in libero ut', 159, 279);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (165, 10, 'pellentesque eget nunc donec quis orci eget', 149, 400);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (166, 7, 'interdum mauris ullamcorper purus sit amet nulla quisque arcu', 107, 467);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (167, 8, 'nulla nisl nunc nisl duis bibendum felis sed', 27, 476);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (168, 4, 'sit amet cursus id turpis integer aliquet massa id lobortis', 37, 325);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (169, 9, 'phasellus sit amet erat nulla tempus vivamus in felis eu', 171, 439);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (170, 9, 'id turpis integer aliquet massa id', 142, 389);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (171, 4, 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi', 186, 289);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (172, 10, 'morbi odio odio elementum eu interdum eu tincidunt', 58, 420);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (173, 4, 'et ultrices posuere cubilia curae nulla dapibus dolor vel', 138, 324);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (174, 9, 'risus auctor sed tristique in tempus sit amet sem fusce', 155, 311);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (175, 5, 'mauris ullamcorper purus sit amet nulla', 15, 375);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (176, 3, 'sit amet diam in magna bibendum imperdiet', 165, 219);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (177, 3, 'odio elementum eu interdum eu tincidunt in leo', 244, 320);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (178, 0, 'curae nulla dapibus dolor vel est donec', 103, 332);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (179, 3, 'nec molestie sed justo pellentesque viverra', 184, 206);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (180, 1, 'velit eu est congue elementum in', 90, 495);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (181, 3, 'diam cras pellentesque volutpat dui maecenas', 68, 302);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (182, 1, 'pulvinar sed nisl nunc rhoncus dui vel', 150, 378);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (183, 3, 'aliquam non mauris morbi non lectus', 75, 345);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (184, 2, 'lorem vitae mattis nibh ligula nec sem duis aliquam', 169, 494);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (185, 7, 'lorem vitae mattis nibh ligula nec sem duis aliquam convallis', 16, 349);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (186, 1, 'pellentesque eget nunc donec quis', 136, 304);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (187, 5, 'augue a suscipit nulla elit ac nulla sed vel', 122, 317);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (188, 8, 'platea dictumst morbi vestibulum velit id pretium iaculis diam erat', 95, 276);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (189, 2, 'in quam fringilla rhoncus mauris enim leo rhoncus sed', 236, 357);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (190, 0, 'maecenas tristique est et tempus semper est quam', 12, 408);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (191, 7, 'rutrum at lorem integer tincidunt', 47, 251);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (192, 5, 'erat vestibulum sed magna at nunc commodo placerat', 81, 321);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (193, 9, 'hac habitasse platea dictumst maecenas ut massa quis augue', 15, 361);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (194, 1, 'venenatis non sodales sed tincidunt eu felis fusce posuere felis', 69, 261);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (195, 3, 'orci nullam molestie nibh in lectus', 54, 268);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (196, 6, 'aenean fermentum donec ut mauris eget massa tempor convallis', 86, 209);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (197, 0, 'vel est donec odio justo sollicitudin ut', 32, 445);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (198, 1, 'sit amet sapien dignissim vestibulum', 95, 381);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (199, 0, 'eu orci mauris lacinia sapien quis libero nullam sit amet', 184, 401);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (200, 9, 'vel sem sed sagittis nam', 65, 394);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (201, 7, 'sapien in sapien iaculis congue vivamus metus arcu adipiscing', 30, 252);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (202, 5, 'faucibus orci luctus et ultrices posuere cubilia', 65, 269);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (203, 8, 'gravida nisi at nibh in hac habitasse platea dictumst', 232, 232);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (204, 6, 'id nisl venenatis lacinia aenean sit amet justo morbi', 115, 344);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (205, 10, 'nascetur ridiculus mus etiam vel', 79, 237);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (206, 6, 'etiam pretium iaculis justo in hac habitasse platea dictumst', 232, 350);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (207, 9, 'sapien non mi integer ac neque duis', 164, 376);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (208, 5, 'magna bibendum imperdiet nullam orci pede venenatis non sodales', 3, 233);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (209, 1, 'pede justo lacinia eget tincidunt eget tempus vel pede morbi', 68, 288);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (210, 10, 'eu interdum eu tincidunt in leo maecenas', 85, 289);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (211, 3, 'massa donec dapibus duis at velit eu', 26, 201);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (212, 9, 'congue eget semper rutrum nulla nunc purus phasellus in', 193, 215);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (213, 0, 'nec sem duis aliquam convallis nunc proin at turpis', 52, 475);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (214, 8, 'erat id mauris vulputate elementum nullam varius', 48, 243);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (215, 9, 'donec diam neque vestibulum eget vulputate ut', 31, 360);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (216, 9, 'sit amet consectetuer adipiscing elit proin interdum mauris', 49, 382);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (217, 9, 'sagittis nam congue risus semper porta volutpat', 134, 327);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (218, 5, 'eget tempus vel pede morbi porttitor lorem', 161, 258);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (219, 9, 'consequat ut nulla sed accumsan felis ut at dolor', 248, 270);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (220, 3, 'cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', 52, 367);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (221, 5, 'in leo maecenas pulvinar lobortis est phasellus sit amet', 196, 456);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (222, 5, 'augue vestibulum ante ipsum primis in faucibus orci', 213, 350);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (223, 9, 'suspendisse potenti nullam porttitor lacus at', 238, 418);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (224, 2, 'felis ut at dolor quis odio consequat varius', 32, 242);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (225, 10, 'primis in faucibus orci luctus et ultrices posuere cubilia curae', 226, 389);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (226, 5, 'magna bibendum imperdiet nullam orci', 93, 410);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (227, 6, 'aliquet maecenas leo odio condimentum id luctus', 233, 326);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (228, 9, 'vestibulum eget vulputate ut ultrices vel augue vestibulum ante', 73, 203);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (229, 1, 'nam nulla integer pede justo lacinia eget', 11, 465);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (230, 10, 'ac consequat metus sapien ut nunc', 173, 387);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (231, 2, 'lobortis convallis tortor risus dapibus augue vel accumsan tellus', 97, 440);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (232, 5, 'tortor sollicitudin mi sit amet lobortis', 39, 347);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (233, 2, 'elit proin interdum mauris non ligula pellentesque ultrices phasellus id', 18, 370);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (234, 4, 'ac enim in tempor turpis nec euismod', 189, 450);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (235, 10, 'elit sodales scelerisque mauris sit amet', 92, 342);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (236, 0, 'integer non velit donec diam', 82, 263);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (237, 8, 'eros elementum pellentesque quisque porta volutpat erat quisque erat eros', 12, 304);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (238, 2, 'lobortis sapien sapien non mi', 68, 499);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (239, 3, 'pellentesque volutpat dui maecenas tristique est et tempus', 92, 372);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (240, 3, 'nec condimentum neque sapien placerat ante nulla', 82, 224);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (241, 1, 'cras in purus eu magna vulputate', 130, 472);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (242, 7, 'scelerisque quam turpis adipiscing lorem vitae', 140, 373);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (243, 3, 'nulla sed vel enim sit amet nunc viverra dapibus nulla', 238, 323);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (244, 1, 'tortor duis mattis egestas metus aenean', 69, 322);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (245, 6, 'a feugiat et eros vestibulum ac est lacinia nisi', 161, 225);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (246, 8, 'diam erat fermentum justo nec condimentum neque sapien', 208, 368);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (247, 2, 'vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis', 212, 372);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (248, 10, 'id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', 120, 472);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (249, 8, 'eget congue eget semper rutrum nulla', 99, 409);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (250, 1, 'risus semper porta volutpat quam pede lobortis ligula', 87, 492);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (251, 1, 'convallis duis consequat dui nec nisi', 66, 404);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (252, 5, 'aliquam sit amet diam in', 232, 210);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (253, 9, 'nulla nisl nunc nisl duis bibendum felis sed interdum', 221, 202);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (254, 6, 'nulla integer pede justo lacinia eget tincidunt eget tempus', 208, 222);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (255, 0, 'lorem vitae mattis nibh ligula nec sem duis aliquam', 176, 413);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (256, 2, 'pulvinar sed nisl nunc rhoncus dui', 215, 217);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (257, 0, 'imperdiet nullam orci pede venenatis non', 97, 326);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (258, 2, 'mattis pulvinar nulla pede ullamcorper augue a', 4, 438);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (259, 2, 'nulla tempus vivamus in felis eu sapien', 190, 383);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (260, 1, 'non lectus aliquam sit amet diam in magna bibendum', 224, 300);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (261, 8, 'velit donec diam neque vestibulum eget vulputate', 167, 286);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (262, 8, 'nisl venenatis lacinia aenean sit amet', 46, 400);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (263, 7, 'pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis', 21, 325);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (264, 9, 'in lectus pellentesque at nulla', 96, 433);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (265, 1, 'primis in faucibus orci luctus et ultrices posuere', 149, 295);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (266, 9, 'praesent blandit nam nulla integer pede justo lacinia eget', 179, 260);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (267, 5, 'accumsan tellus nisi eu orci mauris lacinia', 144, 380);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (268, 3, 'et ultrices posuere cubilia curae donec pharetra', 106, 287);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (269, 9, 'turpis eget elit sodales scelerisque', 62, 417);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (270, 7, 'nunc commodo placerat praesent blandit nam nulla integer pede justo', 196, 417);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (271, 8, 'lectus vestibulum quam sapien varius ut blandit', 202, 250);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (272, 7, 'in hac habitasse platea dictumst etiam', 101, 200);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (273, 3, 'eget vulputate ut ultrices vel', 99, 280);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (274, 1, 'vitae ipsum aliquam non mauris', 93, 225);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (275, 3, 'mauris morbi non lectus aliquam sit amet diam in', 92, 275);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (276, 7, 'vestibulum ante ipsum primis in faucibus', 58, 220);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (277, 1, 'nibh fusce lacus purus aliquet at', 111, 317);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (278, 4, 'nulla ac enim in tempor turpis nec euismod', 147, 466);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (279, 8, 'porttitor id consequat in consequat ut nulla sed accumsan felis', 28, 219);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (280, 7, 'erat nulla tempus vivamus in', 193, 461);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (281, 4, 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu', 168, 465);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (282, 4, 'at feugiat non pretium quis lectus suspendisse potenti in', 20, 419);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (283, 4, 'odio elementum eu interdum eu tincidunt in', 46, 467);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (284, 10, 'at ipsum ac tellus semper interdum mauris ullamcorper', 34, 368);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (285, 8, 'cum sociis natoque penatibus et magnis', 100, 242);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (286, 8, 'lacinia sapien quis libero nullam sit', 194, 480);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (287, 9, 'amet erat nulla tempus vivamus in felis eu sapien', 183, 459);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (288, 0, 'nulla facilisi cras non velit', 51, 477);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (289, 9, 'cras pellentesque volutpat dui maecenas', 130, 254);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (290, 6, 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis', 202, 335);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (291, 1, 'diam vitae quam suspendisse potenti', 176, 345);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (292, 0, 'non ligula pellentesque ultrices phasellus id', 41, 222);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (293, 0, 'in sagittis dui vel nisl', 43, 435);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (294, 3, 'lectus aliquam sit amet diam in magna bibendum', 134, 371);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (295, 5, 'diam cras pellentesque volutpat dui maecenas tristique est', 35, 476);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (296, 4, 'nam nulla integer pede justo', 173, 293);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (297, 2, 'pede libero quis orci nullam molestie', 224, 264);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (298, 2, 'dictumst maecenas ut massa quis augue luctus', 211, 254);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (299, 5, 'dolor morbi vel lectus in quam fringilla rhoncus mauris enim', 137, 234);
insert into calificacion_comprador (calificacion_id, calificacion, comentarios, comprador_id, vendedor_id) values (300, 6, 'rutrum at lorem integer tincidunt ante vel ipsum', 220, 338);
