insert into comprador (usuario_id, descripcion, ocupacion_id) values (1, 'a nibh in quis justo maecenas rhoncus aliquam lacus', 64);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (2, 'ac est lacinia nisi venenatis', 16);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (3, 'donec posuere metus vitae ipsum aliquam non mauris', 95);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (4, 'nisl duis ac nibh fusce lacus purus aliquet at feugiat', 92);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (5, 'non interdum in ante vestibulum ante ipsum primis in', 62);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (6, 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus', 99);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (7, 'mollis molestie lorem quisque ut erat curabitur gravida nisi', 63);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (8, 'vestibulum rutrum rutrum neque aenean auctor gravida sem praesent', 33);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (9, 'pede ac diam cras pellentesque', 21);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (10, 'donec pharetra magna vestibulum aliquet ultrices erat', 13);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (11, 'morbi quis tortor id nulla ultrices aliquet', 70);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (12, 'diam id ornare imperdiet sapien', 64);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (13, 'sed augue aliquam erat volutpat in congue etiam justo', 89);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (14, 'posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis', 28);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (15, 'in hac habitasse platea dictumst etiam faucibus cursus urna', 25);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (16, 'porttitor pede justo eu massa donec dapibus duis at velit', 52);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (17, 'donec odio justo sollicitudin ut suscipit a feugiat et', 37);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (18, 'dictumst morbi vestibulum velit id pretium', 83);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (19, 'a libero nam dui proin leo', 30);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (20, 'velit donec diam neque vestibulum eget', 5);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (21, 'non interdum in ante vestibulum ante ipsum', 59);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (22, 'primis in faucibus orci luctus et ultrices', 98);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (23, 'sit amet eleifend pede libero quis', 85);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (24, 'lectus suspendisse potenti in eleifend quam a', 7);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (25, 'orci eget orci vehicula condimentum curabitur in libero ut', 69);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (26, 'sapien placerat ante nulla justo aliquam', 63);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (27, 'quis lectus suspendisse potenti in eleifend', 45);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (28, 'magna ac consequat metus sapien ut nunc vestibulum ante', 19);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (29, 'posuere felis sed lacus morbi sem mauris laoreet ut', 85);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (30, 'velit id pretium iaculis diam erat', 23);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (31, 'in felis donec semper sapien a', 94);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (32, 'justo etiam pretium iaculis justo in hac habitasse platea dictumst', 96);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (33, 'volutpat eleifend donec ut dolor morbi vel lectus in quam', 56);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (34, 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum', 74);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (35, 'mi integer ac neque duis bibendum', 65);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (36, 'in blandit ultrices enim lorem', 92);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (37, 'donec dapibus duis at velit eu est congue elementum in', 48);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (38, 'nulla suspendisse potenti cras in purus eu magna vulputate', 77);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (39, 'nibh ligula nec sem duis aliquam convallis nunc proin at', 76);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (40, 'dapibus augue vel accumsan tellus nisi eu orci mauris', 66);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (41, 'id nulla ultrices aliquet maecenas leo odio', 70);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (42, 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu', 94);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (43, 'tristique in tempus sit amet', 8);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (44, 'tristique fusce congue diam id ornare imperdiet sapien', 91);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (45, 'venenatis non sodales sed tincidunt eu', 95);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (46, 'dictumst aliquam augue quam sollicitudin', 37);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (47, 'a odio in hac habitasse platea dictumst maecenas', 51);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (48, 'nec molestie sed justo pellentesque viverra pede ac diam', 100);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (49, 'id consequat in consequat ut', 53);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (50, 'molestie lorem quisque ut erat curabitur gravida', 17);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (51, 'gravida nisi at nibh in hac', 16);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (52, 'nisi volutpat eleifend donec ut dolor morbi', 75);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (53, 'sit amet eleifend pede libero quis orci nullam', 96);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (54, 'sagittis dui vel nisl duis ac nibh', 93);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (55, 'morbi non lectus aliquam sit', 95);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (56, 'mi pede malesuada in imperdiet et commodo vulputate justo', 8);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (57, 'a libero nam dui proin', 39);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (58, 'augue quam sollicitudin vitae consectetuer eget rutrum', 25);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (59, 'tristique est et tempus semper est quam pharetra', 91);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (60, 'nisl venenatis lacinia aenean sit amet justo', 6);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (61, 'pede justo eu massa donec dapibus duis at', 80);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (62, 'leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices', 52);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (63, 'mi nulla ac enim in tempor turpis nec', 34);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (64, 'odio elementum eu interdum eu tincidunt in leo maecenas', 53);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (65, 'sit amet turpis elementum ligula vehicula consequat morbi a ipsum', 84);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (66, 'consequat ut nulla sed accumsan felis ut', 86);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (67, 'pretium quis lectus suspendisse potenti in eleifend quam a', 84);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (68, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 86);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (69, 'nulla tellus in sagittis dui vel nisl duis', 19);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (70, 'lacinia aenean sit amet justo morbi ut odio cras', 22);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (71, 'congue eget semper rutrum nulla nunc', 23);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (72, 'faucibus orci luctus et ultrices posuere cubilia curae duis faucibus', 68);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (73, 'laoreet ut rhoncus aliquet pulvinar sed', 53);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (74, 'dapibus duis at velit eu est', 20);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (75, 'duis bibendum felis sed interdum venenatis turpis', 8);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (76, 'vel nulla eget eros elementum pellentesque quisque porta volutpat', 25);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (77, 'turpis a pede posuere nonummy', 83);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (78, 'ut volutpat sapien arcu sed augue', 31);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (79, 'in faucibus orci luctus et ultrices', 68);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (80, 'quam pharetra magna ac consequat metus sapien ut nunc', 17);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (81, 'molestie nibh in lectus pellentesque at nulla suspendisse potenti', 54);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (82, 'id luctus nec molestie sed', 80);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (83, 'convallis duis consequat dui nec nisi volutpat eleifend donec ut', 64);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (84, 'gravida sem praesent id massa id nisl', 85);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (85, 'eu massa donec dapibus duis at velit eu est', 54);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (86, 'ultrices posuere cubilia curae nulla dapibus dolor vel est donec', 65);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (87, 'justo lacinia eget tincidunt eget tempus vel', 72);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (88, 'eget tincidunt eget tempus vel pede morbi porttitor lorem id', 57);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (89, 'morbi vel lectus in quam', 41);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (90, 'suspendisse potenti cras in purus eu magna vulputate luctus cum', 72);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (91, 'phasellus in felis donec semper sapien', 19);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (92, 'ipsum primis in faucibus orci', 23);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (93, 'vivamus vel nulla eget eros elementum pellentesque', 12);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (94, 'sapien placerat ante nulla justo aliquam quis turpis', 41);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (95, 'orci pede venenatis non sodales sed tincidunt eu felis fusce', 97);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (96, 'ligula sit amet eleifend pede libero quis', 78);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (97, 'ornare imperdiet sapien urna pretium', 26);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (98, 'et ultrices posuere cubilia curae', 21);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (99, 'varius integer ac leo pellentesque', 51);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (100, 'nisl duis bibendum felis sed', 10);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (101, 'feugiat non pretium quis lectus suspendisse', 62);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (102, 'dolor quis odio consequat varius integer ac leo pellentesque ultrices', 98);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (103, 'rhoncus sed vestibulum sit amet', 33);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (104, 'mattis nibh ligula nec sem duis aliquam convallis nunc', 16);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (105, 'sollicitudin ut suscipit a feugiat et eros vestibulum ac', 40);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (106, 'sapien iaculis congue vivamus metus arcu adipiscing', 9);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (107, 'lorem quisque ut erat curabitur gravida nisi at', 37);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (108, 'curabitur convallis duis consequat dui', 82);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (109, 'lorem vitae mattis nibh ligula', 28);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (110, 'sapien iaculis congue vivamus metus', 94);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (111, 'velit donec diam neque vestibulum eget vulputate ut', 44);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (112, 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas', 73);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (113, 'ut massa quis augue luctus tincidunt nulla', 27);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (114, 'posuere cubilia curae mauris viverra diam vitae quam suspendisse', 14);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (115, 'eget rutrum at lorem integer tincidunt ante vel ipsum', 74);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (116, 'turpis sed ante vivamus tortor duis mattis', 1);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (117, 'at nunc commodo placerat praesent blandit', 76);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (118, 'lorem vitae mattis nibh ligula nec', 37);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (119, 'gravida sem praesent id massa id nisl venenatis', 41);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (120, 'erat id mauris vulputate elementum nullam varius nulla facilisi', 71);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (121, 'massa id lobortis convallis tortor risus dapibus augue', 98);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (122, 'cras non velit nec nisi vulputate nonummy maecenas tincidunt', 99);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (123, 'curae mauris viverra diam vitae quam', 12);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (124, 'nulla justo aliquam quis turpis eget elit sodales', 44);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (125, 'consequat metus sapien ut nunc vestibulum ante ipsum primis', 45);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (126, 'placerat praesent blandit nam nulla', 30);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (127, 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum', 47);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (128, 'sed accumsan felis ut at dolor', 93);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (129, 'amet diam in magna bibendum imperdiet nullam orci', 76);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (130, 'sit amet eleifend pede libero quis orci nullam', 77);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (131, 'felis eu sapien cursus vestibulum proin eu', 65);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (132, 'nam congue risus semper porta volutpat quam', 85);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (133, 'neque libero convallis eget eleifend luctus ultricies eu nibh', 82);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (134, 'vel nisl duis ac nibh fusce lacus purus', 38);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (135, 'ac tellus semper interdum mauris', 86);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (136, 'sed magna at nunc commodo placerat praesent blandit nam nulla', 93);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (137, 'proin interdum mauris non ligula pellentesque ultrices phasellus', 46);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (138, 'cubilia curae mauris viverra diam', 28);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (139, 'venenatis lacinia aenean sit amet justo morbi ut', 48);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (140, 'ultrices posuere cubilia curae duis faucibus', 25);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (141, 'leo maecenas pulvinar lobortis est phasellus sit amet', 93);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (142, 'eget congue eget semper rutrum nulla', 74);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (143, 'turpis adipiscing lorem vitae mattis nibh ligula nec sem duis', 41);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (144, 'est et tempus semper est quam pharetra', 14);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (145, 'sed ante vivamus tortor duis mattis egestas metus aenean fermentum', 4);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (146, 'pede justo eu massa donec dapibus', 18);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (147, 'felis sed interdum venenatis turpis enim blandit mi in', 87);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (148, 'nunc nisl duis bibendum felis sed', 61);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (149, 'leo odio condimentum id luctus', 21);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (150, 'adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque', 64);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (151, 'porttitor pede justo eu massa donec dapibus duis', 44);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (152, 'pharetra magna vestibulum aliquet ultrices erat tortor', 14);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (153, 'mauris ullamcorper purus sit amet nulla quisque arcu libero', 77);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (154, 'in tempor turpis nec euismod scelerisque quam turpis', 50);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (155, 'non sodales sed tincidunt eu', 70);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (156, 'ultrices posuere cubilia curae mauris', 57);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (157, 'at vulputate vitae nisl aenean lectus pellentesque eget nunc', 29);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (158, 'pretium nisl ut volutpat sapien arcu sed augue aliquam', 62);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (159, 'a odio in hac habitasse', 35);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (160, 'donec semper sapien a libero nam dui', 8);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (161, 'potenti cras in purus eu magna', 27);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (162, 'in ante vestibulum ante ipsum primis', 44);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (163, 'primis in faucibus orci luctus', 67);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (164, 'nullam sit amet turpis elementum ligula', 53);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (165, 'faucibus accumsan odio curabitur convallis duis consequat dui nec', 39);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (166, 'cras non velit nec nisi vulputate nonummy maecenas', 80);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (167, 'massa tempor convallis nulla neque', 47);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (168, 'parturient montes nascetur ridiculus mus etiam vel', 26);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (169, 'dis parturient montes nascetur ridiculus mus', 87);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (170, 'nulla nunc purus phasellus in felis donec semper sapien', 54);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (171, 'vestibulum ante ipsum primis in', 54);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (172, 'vulputate vitae nisl aenean lectus pellentesque eget', 60);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (173, 'etiam vel augue vestibulum rutrum', 26);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (174, 'vel dapibus at diam nam tristique tortor eu', 26);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (175, 'maecenas rhoncus aliquam lacus morbi quis tortor id nulla', 81);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (176, 'viverra dapibus nulla suscipit ligula in lacus curabitur at', 24);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (177, 'ultrices mattis odio donec vitae nisi nam ultrices libero non', 32);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (178, 'diam id ornare imperdiet sapien urna pretium nisl ut', 26);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (179, 'aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas', 98);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (180, 'phasellus sit amet erat nulla tempus vivamus in', 83);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (181, 'quam pede lobortis ligula sit amet eleifend pede', 44);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (182, 'libero rutrum ac lobortis vel dapibus at diam', 57);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (183, 'ridiculus mus vivamus vestibulum sagittis sapien cum', 13);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (184, 'praesent id massa id nisl venenatis lacinia aenean sit amet', 51);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (185, 'quis augue luctus tincidunt nulla mollis molestie', 46);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (186, 'nisl aenean lectus pellentesque eget nunc donec quis orci eget', 54);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (187, 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', 60);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (188, 'ut at dolor quis odio consequat varius integer', 8);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (189, 'diam id ornare imperdiet sapien urna pretium', 90);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (190, 'volutpat erat quisque erat eros viverra eget congue eget', 92);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (191, 'in sagittis dui vel nisl duis ac nibh', 27);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (192, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 37);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (193, 'neque sapien placerat ante nulla justo aliquam quis turpis', 56);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (194, 'est risus auctor sed tristique', 22);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (195, 'rutrum neque aenean auctor gravida sem praesent id massa', 95);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (196, 'pellentesque ultrices mattis odio donec vitae nisi', 94);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (197, 'varius integer ac leo pellentesque ultrices mattis odio donec vitae', 84);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (198, 'duis faucibus accumsan odio curabitur', 94);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (199, 'aliquam convallis nunc proin at turpis a pede posuere nonummy', 84);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (200, 'vulputate ut ultrices vel augue vestibulum ante ipsum', 44);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (201, 'vel nisl duis ac nibh fusce', 33);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (202, 'sem sed sagittis nam congue risus semper porta', 12);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (203, 'varius integer ac leo pellentesque ultrices mattis odio donec vitae', 63);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (204, 'luctus rutrum nulla tellus in sagittis', 89);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (205, 'imperdiet sapien urna pretium nisl ut', 73);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (206, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit', 53);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (207, 'id justo sit amet sapien dignissim', 77);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (208, 'nec nisi volutpat eleifend donec', 58);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (209, 'pretium quis lectus suspendisse potenti', 67);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (210, 'eu orci mauris lacinia sapien quis', 49);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (211, 'rhoncus aliquet pulvinar sed nisl nunc', 27);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (212, 'eros vestibulum ac est lacinia', 78);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (213, 'lacus at velit vivamus vel nulla eget', 97);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (214, 'vivamus vel nulla eget eros elementum pellentesque', 52);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (215, 'maecenas pulvinar lobortis est phasellus sit amet', 59);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (216, 'quis orci eget orci vehicula condimentum curabitur', 81);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (217, 'in quam fringilla rhoncus mauris enim leo rhoncus', 2);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (218, 'dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien', 9);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (219, 'eget elit sodales scelerisque mauris sit', 59);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (220, 'in felis donec semper sapien a libero nam dui proin', 40);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (221, 'dolor morbi vel lectus in quam fringilla rhoncus mauris', 28);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (222, 'maecenas rhoncus aliquam lacus morbi quis tortor id nulla', 93);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (223, 'ac lobortis vel dapibus at diam', 52);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (224, 'quis libero nullam sit amet turpis elementum', 44);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (225, 'sem sed sagittis nam congue risus semper porta', 41);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (226, 'tempor turpis nec euismod scelerisque quam turpis', 54);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (227, 'nonummy integer non velit donec diam neque vestibulum eget', 31);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (228, 'mattis egestas metus aenean fermentum donec ut mauris eget', 25);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (229, 'rutrum rutrum neque aenean auctor gravida sem praesent', 53);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (230, 'porttitor id consequat in consequat ut', 76);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (231, 'natoque penatibus et magnis dis parturient', 79);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (232, 'rhoncus dui vel sem sed sagittis nam congue', 94);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (233, 'ultrices posuere cubilia curae donec', 51);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (234, 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed', 70);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (235, 'tristique fusce congue diam id ornare imperdiet sapien urna', 40);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (236, 'dictumst maecenas ut massa quis augue luctus', 73);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (237, 'eleifend quam a odio in', 60);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (238, 'justo sit amet sapien dignissim vestibulum vestibulum', 16);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (239, 'id consequat in consequat ut nulla', 58);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (240, 'purus phasellus in felis donec semper sapien', 41);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (241, 'id nulla ultrices aliquet maecenas leo', 80);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (242, 'porttitor pede justo eu massa donec dapibus', 55);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (243, 'quisque porta volutpat erat quisque erat eros viverra eget', 28);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (244, 'eu massa donec dapibus duis', 19);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (245, 'mattis pulvinar nulla pede ullamcorper', 21);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (246, 'eget eleifend luctus ultricies eu nibh', 48);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (247, 'sed ante vivamus tortor duis mattis', 1);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (248, 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet', 39);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (249, 'sem fusce consequat nulla nisl nunc nisl', 61);
insert into comprador (usuario_id, descripcion, ocupacion_id) values (250, 'risus dapibus augue vel accumsan tellus nisi eu orci', 53);
