insert into ocupacion (ocupacion_id, clave, descripcion) values (1, 'teacher', 'ultrices aliquet maecenas leo odio');
insert into ocupacion (ocupacion_id, clave, descripcion) values (2, 'doctor', 'lectus pellentesque at nulla suspendisse potenti cras in');
insert into ocupacion (ocupacion_id, clave, descripcion) values (3, 'engineer', 'sit amet eros suspendisse accumsan tortor quis turpis');
insert into ocupacion (ocupacion_id, clave, descripcion) values (4, 'artist', 'semper interdum mauris ullamcorper purus sit');
insert into ocupacion (ocupacion_id, clave, descripcion) values (5, 'chef', 'hendrerit at vulputate vitae nisl aenean');
insert into ocupacion (ocupacion_id, clave, descripcion) values (6, 'pilot', 'dolor sit amet consectetuer adipiscing');
insert into ocupacion (ocupacion_id, clave, descripcion) values (7, 'firefighter', 'amet nulla quisque arcu libero rutrum ac lobortis vel');
insert into ocupacion (ocupacion_id, clave, descripcion) values (8, 'athlete', 'tempus semper est quam pharetra magna ac');
insert into ocupacion (ocupacion_id, clave, descripcion) values (9, 'musician', 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi');
insert into ocupacion (ocupacion_id, clave, descripcion) values (10, 'writer', 'quam a odio in hac habitasse platea dictumst maecenas ut');
insert into ocupacion (ocupacion_id, clave, descripcion) values (11, 'scientist', 'condimentum neque sapien placerat ante nulla');
insert into ocupacion (ocupacion_id, clave, descripcion) values (12, 'lawyer', 'sagittis dui vel nisl duis ac nibh');
insert into ocupacion (ocupacion_id, clave, descripcion) values (13, 'police officer', 'quis turpis eget elit sodales scelerisque mauris sit amet eros');
insert into ocupacion (ocupacion_id, clave, descripcion) values (14, 'mechanic', 'molestie nibh in lectus pellentesque at nulla');
insert into ocupacion (ocupacion_id, clave, descripcion) values (15, 'entrepreneur', 'lorem ipsum dolor sit amet consectetuer');
insert into ocupacion (ocupacion_id, clave, descripcion) values (16, 'designer', 'tincidunt nulla mollis molestie lorem quisque ut erat curabitur');
insert into ocupacion (ocupacion_id, clave, descripcion) values (17, 'nurse', 'libero ut massa volutpat convallis morbi odio odio elementum eu');
insert into ocupacion (ocupacion_id, clave, descripcion) values (18, 'veterinarian', 'velit id pretium iaculis diam erat fermentum justo');
insert into ocupacion (ocupacion_id, clave, descripcion) values (19, 'electrician', 'vel pede morbi porttitor lorem id ligula');
insert into ocupacion (ocupacion_id, clave, descripcion) values (20, 'plumber', 'massa donec dapibus duis at velit eu est congue elementum');
