insert into vendedor (usuario_id, tipo, direccion, calificacion) values (200, 'empresa', '3 Prairieview Park', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (201, 'Persona Fisica', '2312 Hauk Court', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (202, 'Persona Fisica', '59 American Terrace', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (203, 'Persona Fisica', '837 Mendota Parkway', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (204, 'Persona Fisica', '48 Bultman Road', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (205, 'Persona Fisica', '07 Carpenter Hill', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (206, 'Persona Fisica', '54 Brentwood Alley', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (207, 'empresa', '611 Lillian Junction', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (208, 'Persona Fisica', '16 International Court', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (209, 'Persona Fisica', '48467 Monument Road', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (210, 'empresa', '05 Thompson Alley', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (211, 'empresa', '2349 Schlimgen Plaza', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (212, 'Persona Fisica', '77723 Warner Circle', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (213, 'Persona Fisica', '34763 Sherman Trail', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (214, 'Persona Fisica', '1270 Pine View Point', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (215, 'Persona Fisica', '4 Leroy Way', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (216, 'empresa', '3722 Warbler Court', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (217, 'empresa', '89931 Tennyson Crossing', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (218, 'empresa', '0 Darwin Circle', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (219, 'empresa', '29 Burning Wood Road', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (220, 'Persona Fisica', '53 Gulseth Place', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (221, 'empresa', '607 Haas Junction', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (222, 'Persona Fisica', '3 North Plaza', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (223, 'empresa', '183 Park Meadow Hill', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (224, 'Persona Fisica', '20913 Maple Way', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (225, 'empresa', '858 Arkansas Avenue', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (226, 'Persona Fisica', '94164 Parkside Street', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (227, 'Persona Fisica', '23202 Everett Terrace', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (228, 'Persona Fisica', '7179 Forster Hill', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (229, 'Persona Fisica', '5746 Bowman Crossing', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (230, 'empresa', '0 Lakeland Lane', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (231, 'Persona Fisica', '1 Monument Circle', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (232, 'Persona Fisica', '936 Hintze Drive', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (233, 'Persona Fisica', '403 Sherman Park', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (234, 'Persona Fisica', '5 Myrtle Pass', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (235, 'Persona Fisica', '612 Montana Court', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (236, 'empresa', '0 School Court', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (237, 'Persona Fisica', '06 Westerfield Plaza', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (238, 'empresa', '27 Almo Road', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (239, 'empresa', '2 Myrtle Center', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (240, 'Persona Fisica', '7 Waywood Point', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (241, 'empresa', '0528 Moulton Drive', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (242, 'empresa', '08017 Brown Crossing', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (243, 'empresa', '90 Columbus Avenue', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (244, 'empresa', '31016 Mitchell Lane', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (245, 'Persona Fisica', '28 Grim Point', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (246, 'empresa', '969 West Point', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (247, 'empresa', '215 Independence Drive', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (248, 'Persona Fisica', '410 Erie Trail', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (249, 'empresa', '8 Stuart Park', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (250, 'Persona Fisica', '750 Merchant Pass', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (251, 'empresa', '743 Macpherson Plaza', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (252, 'Persona Fisica', '08500 Hagan Terrace', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (253, 'empresa', '30324 Raven Avenue', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (254, 'Persona Fisica', '9977 Badeau Junction', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (255, 'Persona Fisica', '653 New Castle Terrace', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (256, 'Persona Fisica', '79878 Vernon Hill', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (257, 'empresa', '52 New Castle Park', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (258, 'Persona Fisica', '17 Moulton Road', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (259, 'empresa', '34 Mayer Parkway', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (260, 'Persona Fisica', '67 Schlimgen Road', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (261, 'empresa', '62 La Follette Street', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (262, 'empresa', '0 Toban Terrace', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (263, 'Persona Fisica', '92 Carberry Plaza', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (264, 'Persona Fisica', '103 Pleasure Pass', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (265, 'Persona Fisica', '0 Di Loreto Court', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (266, 'Persona Fisica', '0910 Pennsylvania Lane', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (267, 'empresa', '35 Summerview Place', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (268, 'Persona Fisica', '12 Sage Street', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (269, 'empresa', '56 Pleasure Alley', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (270, 'Persona Fisica', '9094 Sutteridge Lane', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (271, 'empresa', '061 Eagan Avenue', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (272, 'Persona Fisica', '4 Laurel Street', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (273, 'empresa', '2 Buell Junction', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (274, 'Persona Fisica', '82667 Brown Road', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (275, 'empresa', '83046 Florence Way', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (276, 'Persona Fisica', '6 Garrison Center', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (277, 'Persona Fisica', '34555 Cascade Hill', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (278, 'Persona Fisica', '7 Knutson Crossing', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (279, 'Persona Fisica', '6800 Barby Center', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (280, 'empresa', '3430 Jackson Crossing', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (281, 'empresa', '7 Chive Point', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (282, 'Persona Fisica', '9 Carpenter Court', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (283, 'empresa', '4352 Rusk Hill', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (284, 'empresa', '486 Jackson Trail', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (285, 'Persona Fisica', '865 Surrey Park', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (286, 'empresa', '508 Superior Park', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (287, 'Persona Fisica', '1 Canary Alley', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (288, 'Persona Fisica', '25259 Westend Road', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (289, 'Persona Fisica', '5958 Gateway Pass', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (290, 'Persona Fisica', '284 Towne Drive', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (291, 'Persona Fisica', '5685 Main Plaza', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (292, 'Persona Fisica', '6 Melvin Pass', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (293, 'Persona Fisica', '636 Stephen Center', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (294, 'empresa', '45116 Amoth Place', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (295, 'empresa', '3510 Monica Way', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (296, 'Persona Fisica', '53055 Jackson Place', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (297, 'empresa', '69099 Schurz Terrace', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (298, 'empresa', '85 Main Street', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (299, 'Persona Fisica', '7 Upham Trail', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (300, 'empresa', '029 Colorado Crossing', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (301, 'Persona Fisica', '15615 Sunbrook Road', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (302, 'Persona Fisica', '95351 Thierer Place', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (303, 'empresa', '96 Algoma Avenue', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (304, 'Persona Fisica', '84 Old Gate Place', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (305, 'empresa', '146 Monument Plaza', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (306, 'empresa', '56523 Sachtjen Trail', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (307, 'Persona Fisica', '5 Esker Place', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (308, 'empresa', '45639 Main Place', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (309, 'Persona Fisica', '8 Mesta Park', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (310, 'Persona Fisica', '72 Magdeline Way', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (311, 'empresa', '4738 Veith Trail', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (312, 'empresa', '4 Village Green Lane', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (313, 'empresa', '35690 Dwight Point', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (314, 'empresa', '841 Independence Parkway', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (315, 'Persona Fisica', '53410 Comanche Circle', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (316, 'empresa', '41651 Continental Terrace', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (317, 'empresa', '71980 Daystar Center', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (318, 'Persona Fisica', '918 Farragut Hill', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (319, 'Persona Fisica', '7 Northview Pass', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (320, 'Persona Fisica', '03 Redwing Avenue', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (321, 'Persona Fisica', '61 Porter Crossing', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (322, 'empresa', '6 Forster Lane', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (323, 'Persona Fisica', '6425 Farmco Pass', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (324, 'Persona Fisica', '31 Leroy Park', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (325, 'empresa', '47716 Rutledge Center', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (326, 'empresa', '547 Gateway Terrace', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (327, 'Persona Fisica', '39 Caliangt Lane', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (328, 'Persona Fisica', '48823 Vera Hill', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (329, 'Persona Fisica', '58 Transport Parkway', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (330, 'Persona Fisica', '1 Thackeray Road', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (331, 'empresa', '77465 Service Lane', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (332, 'empresa', '74 Glendale Terrace', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (333, 'empresa', '8 Laurel Place', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (334, 'Persona Fisica', '6237 Myrtle Trail', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (335, 'Persona Fisica', '584 Spenser Center', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (336, 'empresa', '862 Browning Avenue', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (337, 'Persona Fisica', '68199 Farmco Trail', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (338, 'Persona Fisica', '0968 Twin Pines Circle', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (339, 'Persona Fisica', '26 Kenwood Point', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (340, 'empresa', '824 Meadow Vale Circle', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (341, 'empresa', '1 Atwood Crossing', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (342, 'Persona Fisica', '3 Grover Place', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (343, 'empresa', '00847 Warbler Junction', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (344, 'empresa', '33 Fieldstone Junction', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (345, 'empresa', '77 Elka Court', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (346, 'empresa', '195 Swallow Terrace', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (347, 'empresa', '56 Sundown Point', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (348, 'Persona Fisica', '2 Clyde Gallagher Point', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (349, 'empresa', '18 Rowland Crossing', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (350, 'Persona Fisica', '1944 Dwight Road', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (351, 'Persona Fisica', '227 Arkansas Alley', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (352, 'Persona Fisica', '67 Alpine Place', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (353, 'empresa', '9678 Debra Point', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (354, 'empresa', '3571 Ridgeview Alley', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (355, 'empresa', '9 Troy Hill', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (356, 'Persona Fisica', '74433 Carey Park', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (357, 'empresa', '4 Chive Way', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (358, 'empresa', '4836 Colorado Place', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (359, 'Persona Fisica', '17 Jana Way', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (360, 'Persona Fisica', '393 Crowley Hill', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (361, 'empresa', '80318 Buena Vista Avenue', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (362, 'Persona Fisica', '4328 Elka Parkway', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (363, 'Persona Fisica', '48 Cody Point', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (364, 'empresa', '18287 Montana Crossing', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (365, 'Persona Fisica', '158 Utah Avenue', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (366, 'empresa', '6 Mosinee Plaza', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (367, 'empresa', '6 Thackeray Lane', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (368, 'Persona Fisica', '6 Comanche Parkway', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (369, 'Persona Fisica', '8 Forest Run Plaza', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (370, 'Persona Fisica', '378 Arrowood Point', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (371, 'empresa', '9631 Glendale Way', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (372, 'empresa', '5676 Mayer Road', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (373, 'empresa', '9764 Bluejay Parkway', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (374, 'Persona Fisica', '9 Hooker Junction', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (375, 'empresa', '51619 East Plaza', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (376, 'Persona Fisica', '0548 Dottie Avenue', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (377, 'Persona Fisica', '5013 Michigan Street', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (378, 'empresa', '024 Del Sol Road', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (379, 'empresa', '1772 Vahlen Road', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (380, 'empresa', '5 Golf Parkway', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (381, 'Persona Fisica', '9 Washington Court', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (382, 'Persona Fisica', '9354 Maryland Alley', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (383, 'Persona Fisica', '3 Aberg Street', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (384, 'empresa', '55595 Bowman Pass', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (385, 'empresa', '3 Saint Paul Street', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (386, 'empresa', '02 Montana Lane', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (387, 'Persona Fisica', '2 Nancy Parkway', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (388, 'empresa', '36404 Heath Circle', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (389, 'empresa', '3 5th Avenue', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (390, 'Persona Fisica', '6 Homewood Lane', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (391, 'empresa', '60 Towne Point', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (392, 'empresa', '61389 Paget Hill', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (393, 'Persona Fisica', '50 Oxford Hill', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (394, 'Persona Fisica', '61310 Pankratz Place', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (395, 'empresa', '34526 Grim Alley', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (396, 'empresa', '62 Forest Run Lane', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (397, 'empresa', '17 Sugar Court', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (398, 'empresa', '4891 Chive Pass', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (399, 'empresa', '8258 Hoard Crossing', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (400, 'empresa', '161 6th Junction', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (401, 'empresa', '32623 Maple Wood Terrace', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (402, 'empresa', '925 Butternut Park', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (403, 'Persona Fisica', '20 Orin Point', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (404, 'empresa', '37302 Division Crossing', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (405, 'empresa', '41936 Northfield Park', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (406, 'empresa', '39 Alpine Way', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (407, 'Persona Fisica', '82578 Bartillon Pass', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (408, 'Persona Fisica', '02 Iowa Road', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (409, 'Persona Fisica', '3 Atwood Alley', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (410, 'empresa', '614 Gateway Trail', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (411, 'Persona Fisica', '44308 Stephen Parkway', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (412, 'empresa', '836 Mccormick Drive', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (413, 'empresa', '9 Harper Road', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (414, 'empresa', '5810 Texas Point', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (415, 'Persona Fisica', '34 Hanover Avenue', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (416, 'empresa', '28 Utah Hill', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (417, 'empresa', '06857 Lake View Avenue', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (418, 'empresa', '42 Larry Alley', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (419, 'empresa', '3401 Artisan Court', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (420, 'Persona Fisica', '79357 Leroy Center', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (421, 'Persona Fisica', '9 Crest Line Alley', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (422, 'Persona Fisica', '4 Rowland Circle', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (423, 'empresa', '828 Meadow Vale Circle', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (424, 'empresa', '4293 Lindbergh Plaza', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (425, 'Persona Fisica', '262 Crest Line Way', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (426, 'empresa', '646 Warbler Junction', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (427, 'Persona Fisica', '00343 New Castle Place', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (428, 'Persona Fisica', '680 Schurz Street', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (429, 'empresa', '6626 Service Center', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (430, 'empresa', '84 Rieder Alley', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (431, 'Persona Fisica', '4273 Kings Junction', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (432, 'Persona Fisica', '2 Grover Center', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (433, 'Persona Fisica', '2009 David Parkway', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (434, 'Persona Fisica', '59 North Place', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (435, 'empresa', '60119 Orin Street', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (436, 'Persona Fisica', '20537 Jackson Hill', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (437, 'Persona Fisica', '528 Quincy Lane', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (438, 'empresa', '5867 Everett Road', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (439, 'empresa', '974 Delaware Lane', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (440, 'Persona Fisica', '24297 Shelley Point', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (441, 'Persona Fisica', '32 Oxford Circle', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (442, 'empresa', '47 Dorton Parkway', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (443, 'Persona Fisica', '02433 Nancy Court', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (444, 'empresa', '47341 Tony Place', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (445, 'Persona Fisica', '95 Fairfield Trail', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (446, 'Persona Fisica', '36688 Barby Junction', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (447, 'empresa', '109 Dwight Crossing', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (448, 'empresa', '10081 Oak Valley Drive', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (449, 'Persona Fisica', '66659 Hoard Lane', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (450, 'Persona Fisica', '8 Stone Corner Junction', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (451, 'empresa', '64 Ramsey Court', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (452, 'empresa', '60751 Oakridge Terrace', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (453, 'empresa', '27322 4th Avenue', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (454, 'Persona Fisica', '59 Continental Plaza', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (455, 'empresa', '4 Spohn Street', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (456, 'Persona Fisica', '39 Debra Hill', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (457, 'Persona Fisica', '01 Nevada Pass', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (458, 'Persona Fisica', '1 Moland Road', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (459, 'Persona Fisica', '6 Grayhawk Park', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (460, 'Persona Fisica', '44 David Junction', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (461, 'Persona Fisica', '7408 Mosinee Street', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (462, 'empresa', '2 Monterey Trail', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (463, 'Persona Fisica', '681 Blue Bill Park Lane', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (464, 'Persona Fisica', '8 Birchwood Road', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (465, 'empresa', '560 Mendota Street', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (466, 'Persona Fisica', '3230 Burrows Terrace', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (467, 'empresa', '7446 1st Terrace', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (468, 'Persona Fisica', '4 Grasskamp Parkway', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (469, 'Persona Fisica', '8 Fuller Street', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (470, 'empresa', '4263 Briar Crest Hill', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (471, 'empresa', '7964 Anzinger Place', 4);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (472, 'empresa', '49762 Chinook Road', 6);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (473, 'Persona Fisica', '4051 Elmside Pass', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (474, 'empresa', '85315 Farwell Way', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (475, 'empresa', '90 Packers Avenue', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (476, 'empresa', '02 Ryan Trail', 1);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (477, 'empresa', '9668 Sullivan Crossing', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (478, 'empresa', '323 Fisk Junction', 10);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (479, 'empresa', '974 Londonderry Way', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (480, 'Persona Fisica', '82708 Moulton Crossing', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (481, 'empresa', '342 Melvin Place', 3);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (482, 'empresa', '1 Melby Drive', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (483, 'Persona Fisica', '910 Hovde Street', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (484, 'Persona Fisica', '1891 Grayhawk Drive', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (485, 'Persona Fisica', '9017 Lake View Plaza', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (486, 'Persona Fisica', '6195 Utah Road', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (487, 'Persona Fisica', '732 Weeping Birch Court', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (488, 'Persona Fisica', '2590 Saint Paul Circle', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (489, 'empresa', '4 Commercial Street', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (490, 'Persona Fisica', '7 Johnson Pass', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (491, 'empresa', '571 Browning Terrace', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (492, 'Persona Fisica', '24 Mesta Place', 7);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (493, 'empresa', '57491 Columbus Pass', 2);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (494, 'empresa', '47350 Declaration Road', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (495, 'empresa', '65 Kings Parkway', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (496, 'Persona Fisica', '06190 Grasskamp Plaza', 9);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (497, 'Persona Fisica', '58037 Corscot Trail', 5);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (498, 'Persona Fisica', '103 Alpine Parkway', 8);
insert into vendedor (usuario_id, tipo, direccion, calificacion) values (499, 'empresa', '37 Debs Crossing', 5);
